#!/bin/bash
# Permissions: chmod +x manage

SCRIPT_DIR="$(dirname "$0")"
ENV_FILE="$SCRIPT_DIR/env.sh"

# 1. Auto-source the environment
if [ -f $ENV_FILE ]; then
    source $ENV_FILE
else
    echo "Error: env.sh not found in the $SCRIPT_DIR."
    exit 1
fi

# 2. Command Dispatcher Logic
cd $BASE_DIR

COMMAND=$1
shift # Move to the next argument

SUB_SCRIPT="$SCRIPTS_DIR/manage-$COMMAND"

if [ -f "$SUB_SCRIPT" ]; then
    "$SUB_SCRIPT" "$@"
elif [ "$COMMAND" == "prune" ]; then
    echo "Cleaning up unused Docker resources..."
    docker system prune -af
else
    echo "Unknown command: ${COMMAND:-(null)}"
    echo "Available: $( (ls "$SCRIPTS_DIR" | sed 's/manage-//'; echo "prune") | sort | xargs )"
    echo "----"
    status_title "HELP"
    echo "Available commands:"
    # This takes the file list and formats it into 3 neat columns
    (ls "$BASE_DIR/scripts" | sed 's/manage-//'; echo "prune") | sort | column -c 60
    echo -e "\nUsage: d [command] [options]"
    exit 1
fi
