#!/bin/bash

source "$(dirname "$0")/../env.sh"
load_stacks

get_target_stacks "$1"

for stack in "${TARGET_STACKS[@]}"; do
    status_title "STARTING: $stack"
    if [ -d "$CONTAINERS_DIR/$stack" ]; then
        project_name=$(echo "$stack" | tr '/' '-')
        (cd "$CONTAINERS_DIR/$stack" && docker compose -p "$project_name" up -d --no-build)
    else
        echo "Directory $stack not found. Skipping..."
    fi
done
