#!/bin/bash

# Sourcing the readable env.sh
source "$(dirname "$0")/../env.sh"

# Use the function we added to env.sh
status_title "DOCKER SYSTEM DASHBOARD"

echo -e "\n[ 1. Container States ]"
# We add .Status (which includes 'Up' and uptime) and .RunningFor
# We also include 'table' to get the headers automatically
docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"

echo -e "\n[ 2. Resource Usage (Snapshot) ]"
# --no-stream ensures it doesn't hang in your terminal
# We format it to focus on the essentials for your laptop
docker stats --no-stream --format "table {{.Name}}\t{{.CPUPerc}}\t{{.MemUsage}}\t{{.NetIO}}"

echo ""
status_title "END OF REPORT"
